[tool.poetry]
name = "crm-vehicle"
version = "0.1.0"
description = ""
authors = ["mattia allegro <mattia.allegro@yahoo.it>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.13"
django = "4.2.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
